import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  const pages = [
    {title: 'Home', url: '/'},
    {title: 'Conveners', url: '/conveners'},
    {title: 'Problems', url: '/problem-statements'},
    {title: 'About Us', url: '/about-us'},
  ]
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
       <Navbar pages={pages}/>
        {children}
      </body>
    </html>
  );
}
